# Generated by Django 6.0.6 on 2026-10-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_techstack_project_tech_stacks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techstack',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stacks',
            field=models.ManyToManyField(related_name='projects', to='projects.techstack'),
        ),
    ]
